class_name ChunkSet
extends Resource
## The player's body pre-diced into chunks, in rig rest space, generated by
## tools/gen_body.gd. Each chunk is a skinned mesh (same bone weights as the
## body), so at death the chunks can be posed exactly like the body and
## swapped in for it.

## One mesh per chunk. Surfaces are named "outside" (the body's skin) and
## "cut" (the flat faces where it was sliced).
@export var meshes: Array[ArrayMesh] = []
